dist: trusty
language: java
jdk:
- oraclejdk8
sudo: required
env: ' MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"  MAVEN_OPTS=''-Xms1g -Xmx2g''  SEQWARE_SETTINGS="${TRAVIS_BUILD_DIR}/seqware_settings" '

git:
  depth: 3

addons:
  sonarcloud:
    organization: "oicr-gsi"
    token: 
        secure: "uuFhewPL++z8b8N73qMdULpLeXsOxerMe5CM0kSAgRlipcbdJhNU3/ucyO6bDvG/juoTYE09NeqRpYlNpDORKUUtWI3XZDqipPrfFsKzUq4vMFA7EatiAorPNxFX+S71TQFLefO+TbKrGJL1l9hOlDPnnbkGFMgvJulKdw8yX0kkX6hJdkylDdVA4kb0tRKwYfyns6zP0pufZyaCmrFCDGL4QQwHVfp7Wolddwgya7sKupmvvCJoDVOUstq2vJlo4SbCSsuusJ4t54oq/tr1sNGj4cE9QjGsSOn+iqA7FvcvnQzdwlq7HAiHuAiMeyXdtqqh/rcioiCoB36s/G0+vPqqHOuOE+msRceMW1L3PMcgmwHhrSPr4vpizU7TSguxhIovdz6aeB9zkbrGAYbnOo21AQBogARLWPjbJP3/XQnspjM58dwI+j5rG4ws/Q2d/g67hg1sxsaqgKu+EfRWfQpAkcCZjmqThPRrj0S2RyIRpAT+XVRu4fCvrXuJ/A5uhFkslfgQFA6nPMZY4JjV13nJmunrMLaUDxw5E083gZvBmJU8Llfy2Am+pqd0nWuyj9ZidsDQQ3hXzwMl+n0+V07AHWIBWHw23HwqE3WWw9/f0ErTodFZlxtvju9VNTQkIKvd08R1rEY4/t4EKLWssSPhMHzU815aPr23Pny3QS4="
    github_token:
        secure: "Y/0fvSQ2LRLoyTpF43aXBQALQRPAzuWUtpYffmKYdTB9syWmqQpKfeFxSzM1wWVxrXwmWo9mQckMfYaDD0V+QAIgEyqqX3SqA4AFB1L7updV5wrKW5A8xaz8+V7HqbkENW17LAFadWb2H4sbnf09x1/mpn1ywcgfXisjDr8DOR7qbBY691xrODLbZgflgoFKrx4JjHVgSAkVkPDwWot6b1w/ikYNoRbe7PHlvu+5lIwJ55hVobm1UJ3O4ScUY7CpNZO7oM6fkV1I+/JqXCxubQB14JvbdBN2MgQxRSy3+NL6VsWQ/TEkgcWxKyNRk+/aLSDjJ77n2mKfUYlf3TG8pH1Ixq/nlxADZyWQwTTpkWxylo3z6YvKh/WFVeT/qZafwgqNmSbSk0aHJbTT/8gEIKJX2kHpSUWjHcGIJOXS+T0RF5GIntymN7XmqMrl1bJTrcpsJ/0rvy4QBG0HOOY/7FK3GqvLGD21WmLgrbFiFkrXrffLqPGpDaHriLqwMRtJP9Br6sO9FQJhU0RZY1q2GHtBXT6kmu3oCTIXLcl2sr6iLvE4KGCiApXq13/YsMsQUMEsK9IOzRmpfdmvmJYD+GfWf77aSZDIR6r21cBDR7geoscXbcLePenR1IJyvGaLv108EJOJ2x9FUwH9ugzUFmd/8eknpL8jw81VDAIClcM="

before_install:
- git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
- cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"

before_script:
- touch "${SEQWARE_SETTINGS}"

script:
  - mvn clean install
  - 'echo "[WARN] SonarCloud is not going to run on pull requests.";'

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
